---
- name: add spotify key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 0DF731E45CE24F27EEEB1450EFDC8610341D9410
  become: yes
- name: add spotify deb repository
  apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
  become: yes
- name: install programs
  apt: name={{item}} state=installed
  with_items:
    - python3.6
    - gdebi
    - pavucontrol
    - vlc
    - xfce4-terminal
    - spotify-client
    - slim
    - htop
    - chromium-browser
    - i3status
    - i3
    - i3lock
    - scrot
    - lxrandr
    - profanity
    - irssi
    - feh
    - shutter
    - nautilus
    - blueman
    - ncdu
    - kazam
  become: yes
- name: install megasync
  apt:
    deb: https://mega.nz/linux/MEGAsync/xUbuntu_17.04/amd64/megasync-xUbuntu_17.04_amd64.deb
  become: yes
- name: install py3status
  pip: 
    name: py3status
