---
- name: add spotify key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: BBEBDCB318AD50EC6865090613B00F1FD2C19886
  become: yes
- name: add spotify deb repository
  apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
  become: yes
- name: install programs
  apt: name={{item}} state=installed
  with_items:
    - gdebi
    - pavucontrol
    - vlc
    - xfce4-terminal
    - transmission-gtk
    - spotify-client
    - xorg
    - slim
    - htop
    - chromium-browser
    - i3status
    - i3
    - i3lock
    - scrot
  become: yes
- name: install atom
  apt:
    deb: https://atom.io/download/deb
  become: yes
