---
- name: install zsh
  apt:
    name: zsh
    state: present
  become: yes
- name: install ohmyzsh
  git:
    repo:  https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh
- name: link ~/.dotfiles/zshrc → ~/.zshrc
  file:
    src: ~/.dotfiles/zshrc
    dest: ~/.zshrc
    state: link
- name: link custom oh-my-zsh theme
  file:
    src: "{{ dotfiles_dir }}/oh-my-zsh/themes/ramonvg.zsh-theme"
    dest: ~/.oh-my-zsh/themes/ramonvg.zsh-theme
    force: yes
    state: link
