---
- name: installing docker dependencies
  apt: name={{item}} state=installed update_cache=yes
  with_items:
  - apt-transport-https
  - ca-certificates
  - python-pip
- name: import repo key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
- name: add deb repository
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"
- name: install docker
  apt: pkg=docker-engine state=installed update_cache=yes
- name: start docker
  service: name=docker state=started
- name: installing docker-compose
  pip:
    name: docker-compose
- name: add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users }}"
